---
# tasks file for ssh
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install ssh
  ansible.builtin.package:
    name:
      - openssh-client
      - openssh-server
    state: present

- name: Disable SSH password authentication and set port
  ansible.builtin.blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      PasswordAuthentication no
      Port {{ ssh_port }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    validate: /usr/sbin/sshd -t -f %s
  notify: Restart sshd

- name: Create .ssh folder
  ansible.builtin.file:
    path: "{{ ssh_dir }}"
    state: directory
    mode: "0700"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_group }}"

- name: Create OpenSSH keypair if it doesn't exist
  community.crypto.openssh_keypair:
    path: "{{ ssh_dir }}/id_rsa"
    regenerate: never
    type: "{{ ssh_key_type }}"
  notify: Restart sshd

- name: Create authorized_keys file
  ansible.builtin.file:
    path: "{{ ssh_dir }}/authorized_keys"
    mode: "0600"
    state: touch
    access_time: preserve
    modification_time: preserve
    owner: "{{ ssh_user }}"
    group: "{{ ssh_group }}"

- name: Set authorized ssh keys
  ansible.builtin.lineinfile:
    path: "{{ ssh_dir }}/authorized_keys"
    regexp: "{{ item }}"
    line: "{{ item }}"
  with_items: "{{ ssh_authorized_keys }}"

- name: Start sshd
  ansible.builtin.systemd:
    name: ssh
    state: started
    enabled: true
